### PR TITLE
Add JSON to codec.

### PR DESCRIPTION
**Pull request by ccorcos**
I'm using a deterministic JSON stringifier to enable encoding JSON objects. However, its not going to be lexicographically sorted this way.

### CODE REVIEW

**Comment by PaulBlanche** [comment]
The way to go would be to define an order on keys of objects, and then "transform" the object to an array of key/value pairs, where key would be the encoded string form the object key and value would be the encoded value.

So `{foo:1, bar:"baz"}`would be encoded as `MJbar"Jbaz"Jfoo"DE500M1!`, assuming `M` and `!` as a delimiters for objects and `"` to separate keys and values. 

Then `{bar:"foobar", foo:2}`would be encoded as `MJbar"Jfoobar"Jfoo"DE500M2!` giving `{foo:1, bar:"baz"} < {bar:"foobar", foo:2}` 

But this take only in account flat objects. For nested object, in order to avoid recursive encoding/decoding that would be taxing on performance, the same trick than for arrays could be used (see #7). So the object `{foo:{bar:'a'}}` would be encoded as `MJfoo"MJbar"Ja!!` 

But then, what about mixing arrays and objects ?
For exemple how would we encode this object : `[{foo:['a','b'}, bar:'b'},'a']` ? Given the current implementation of array encoding, we would walk the top array, and since we don't find any child array, we call encode on each child effectively doing recursive encoding which we are trying to avoid.

So we would need to treat object and arrays the same ways as "nestable structure". Let's say we use `K` and `!` as delimiters for nestable structures (be it objects or arrays). We then need a marker to distinguish arrays from object, so let's say `A` and `O`.
Then let's say that an item of a nestable structure is either an pair of key/value if we are in an object, and just a value if we are in an array.
Using the trick in #7,  we walk the nestable structure as if flattened, but recording the depth with `KO`or `KA`.

Then `[{foo:['a','b'}, bar:'b'},'a']` would be encoded as `KAKOJbar"Jb"Jfoo"KAJa"Jb!!"Ja` in a single pass.
This would be a breaking change since it would change the encoding of arrays, but it would allow encoding deeply nested arrays/object.

Another "simpler" way to go would be for users to store objects as arrays of key/value pairs, ordered by key.

**Comment by dominictarr** [comment]
the format should be compatible with https://github.com/deanlandolt/bytewise which does support objects, I'm not sure if it has deterministic order though. It certainly must be lexiographically sorted though, that's the whole point. (but if you really want to work around that, you can just put your JSON in a string, since charwise already supports strings)

I should probably ask what you are using this for if you don't need lexiographic ordering

**Comment by ccorcos** [comment]
Hmm. What's wrong with just using JSON stringify with sorted keys? Not sure I understand the need for the prefix / postfix...

**Comment by PaulBlanche** [comment]
Well JSON format won't work with numbers. JSON encodes number using their actual representation, so `9`and `10` are encoded as `"9"`and `"10"`. But since we want the ordering to work with lexiographic order, this won't work, because in lexicographic order `"10" < "9"`.
That's why we can't simply use JSON serialization.

We also aim to be compatible with bytewise, where an order amongst types  is defined (for exemple , `null` is inferior to any other types, and `undefined` superior to allow range queries). Using JSON serialization would define another order amongst types (where `null` would fall between `false` and `true`).

**Comment by ccorcos** [comment]
Oh wow, you're right. Sounds good. I'll fix this up then and get back to you.

**Pull request closed without merging**
