### PR TITLE
Fix/escaping

### PR DESCRIPTION
**Pull request by PaulBlanche**
Should fix escaping problem with nested arrays :
* Array separator `!` is escaped as `??`
* Escaping symbol `?` is escaped as `?@`
That way, when a `!` is met, we can be sure it is an array seperator for
the current "level" of nested array.

### CODE REVIEW

**Comment by dominictarr** [comment]
okay, I'm gonna merge this - as a breaking change because the escape changes.

I think the time complexity of encoding/decoding nested arrays could be improved. say we have a deeply nested array, the array splitters on the third array deep are `?@?@` and the forth are `?@@?@@`, and escape is called on each item in the array many times until there is no more... my intuition is that if we could do it as a single pass it would be better.

I got some easy wins by just testing if the array doesn't need escaping by using a simple regexp (because that is faster than a for loop to check every character.

merged into 2.0.0

**Comment by PaulBlanche** [comment]
Yeah, you are right, knowing the depth of the array, the correct escape could be done in one pass while encoding : 
* `!` at depth 0 (so an array splitter at root level) gives `!` 
* `?` at depth 0 can't occur
* `!` at depth 1 (so an array splitter at level 1 or in a string at root level) gives `??` 
* `?` at depth 1 (in a string at root level) gives `?@`
* `!` at depth 2 (so an array splitter at level 2 or in a string at level 1) gives `?@?@`
* `?` at depth 2 (in a string at level 1) gives `?@@`
* ...

For unescaping while decoding, maybe we could count keep track of the depth while reading the encoded string using the array tag `K`, and if an escaped `!` match the same depth, then it must be an array splitter : 
* at level 2 `?@@?@@` can't be a splitter, so it must be part of a string or deeper array
* at level 3 though `?@@?@@` must be a splitter

The problem is keeping track of the depth. Since there is no array ending mark, it might be difficult to know where a nested array ends.

**Comment by dominictarr** [comment]
is the solution then to add an array ending mark?

**Comment by PaulBlanche** [comment]
I'll try and do that, but it will be another breaking change.

**Comment by PaulBlanche** [comment]
After experimenting a bit, i found that an array endingmark would work, but i needed to change the array splitter to keep the order : the array ending mark should be inferior to the array splitter (so `['a']` stay inferior to `['a','b']` for exemple). But overall it passes the tests.

I will open a push request after I clean the code. Meanwhile, I have a few questions :

* should the escaping be done with loop or a replace with regexp ? I understand that a test on a string with a regexp is quicker than a loop, but what about a replacement ? 
* if we replace with regexp, does it make sens to check items that need escaping with a regexp ? I'd say it depends on the frequency of the symbols to escape, wich leads me to the last question
* since the change will be a breaking change, what mark should we use for splitter and array ending mark ? (keeping in mind that `ending < splitter` and that those should be unfrequent chars)

**Comment by dominictarr** [comment]
I'm not sure which is faster, you'll have to measure it.

> ...and that those should be unfrequent chars
great point! for my main use case, a lot of the content I plan on using this with will be base64 (ssb ids) so a non base64 [a-zA-Z0-9/+=] would be ideal... and also none of `.#@&`.

I used `!` because it's the lowest visible character... the next is `"`, so you could use `"` as the splitter and '!' as the terminator. those are unfortunately both fairly common in normal text, but I not likely to be found in property names, and likely to be stripped from a database index (one of the common usecases for something like charwise)

**Comment by dominictarr** [comment]
another completely different idea: parse backwards, with length delimiters. so no escapes are necessary, but when lexiographically comparing forwards - the length tags don't interfere. But prehaps we should take the current approach as far as it will go and then try maybe backwards as a different module

**Comment by PaulBlanche** [comment]
Small update : 
Desatrous performance when decoding using my strategy. Looping is definitly a bad idea.

Another idea : flatten the array but prefix/postfix each item with its depth. Decoding is done by splitting once one the separator, then looping over each item to decode it (simple operation since each item should be a primitive) and place it at appropriate depth in the result array. Should be fast enough ?

**Comment by dominictarr** [comment]
OH! That's a great idea!

That idea suddenly reminds me of parquet.
I was working on a javascript implementation... and I saw a bit that sounded like that.
parquet is based on google dremel, there is a paper about it: https://research.google.com/pubs/pub36632.html I don't think you need to read that to implement this though.

**Comment by PaulBlanche** [comment]
well, i tried this idea and it outperforms the actual implementation on my computer with deeply nested array ( ~ 10 levels, 0 to 8 length on each level) : 
```
new encode      43263
old encode      15538
new decode      35517
old decode      8322
```
however, on simpler arrays ( ~ 2 levels, 0 to 8 length on each level) : 
```
new encode      107218
old encode      159882
new decode      85964
old decode      67942
```
It might be my quick and dirty implementation that is at fault. I'll open a merge request with it anyway.

**Pull request merged**
