### PR TITLE
Better number handling

### PR DESCRIPTION
**Pull request by PaulBlanche**
Issue #1 comes from the fact that with a big enough numbers, `toString()` gives its scientific notation. Since this notation is unique for each number (except 0) it can be the basis for encoding

Number is split in exponent and mantissa :
- Exponent is an integer in [-324, 308]. An offset of 500 allow us to work with positive exponents.
- Mantissa is a decimal in ]-10, 10[. A trail of 0s allow to exceed precision, wich makes two mantissa of the same sign order well lexicograhpiccally.

Nines' complement is still used to order negative numbers.

Additionnaly, `Nan`, `+Infinity` and `-Infinity` are handled.

### CODE REVIEW

**Comment by dominictarr** [comment]
can we use ES5 for this?
node@6 gets  `TypeError: String(...).padStart is not a function`
this is a low level library so it's better that it just runs on everything without compiling.

**Comment by dominictarr** [comment]
otherwise, this looks really good though!

**Comment by PaulBlanche** [comment]
ok, i'll downgrade to ES5.
Would it be ok to add a test for ES version, using [check-ecmascript-version-compatibility](https://github.com/EvanHahn/check-ecmascript-version-compatibility) for exemple ?

**Comment by dominictarr** [comment]
sure, sounds great!

**Comment by PaulBlanche** [comment]
ES5 compatible, with tests to prove it :)

**Comment by PaulBlanche** [comment]
now ES5 complient, with tests to prove it :)

**Comment by dominictarr** [comment]
thanks! merged into 0.1.1

**Pull request merged**
